import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import {
  importedPackages,
  packageNameOf,
  stripComments,
} from "./manifest-hygiene";

describe("stripComments", () => {
  it("drops a line comment", () => {
    expect(stripComments('// import x from "ghost";\nconst a = 1;')).toBe(
      "\nconst a = 1;",
    );
  });

  it("drops a block comment spanning several lines", () => {
    expect(
      stripComments('/*\n * import x from "ghost";\n */\nconst a = 1;'),
    ).toBe("\nconst a = 1;");
  });

  it("does not truncate a line at the // inside a URL", () => {
    const source = 'const u = "https://example.test/x";';
    expect(stripComments(source)).toBe(source);
  });
});

describe("packageNameOf", () => {
  it("keeps a bare package name as-is", () => {
    expect(packageNameOf("dotenv")).toBe("dotenv");
  });

  it("drops the subpath of a deep import", () => {
    expect(packageNameOf("dotenv/config")).toBe("dotenv");
  });

  it("keeps both segments of a scoped package", () => {
    expect(packageNameOf("@prisma/client")).toBe("@prisma/client");
  });

  it("drops the subpath of a scoped deep import", () => {
    expect(packageNameOf("@testing-library/jest-dom/vitest")).toBe(
      "@testing-library/jest-dom",
    );
  });
});

describe("importedPackages", () => {
  it("finds a side-effect import", () => {
    expect(importedPackages('import "dotenv/config";')).toEqual(["dotenv"]);
  });

  it("finds default, named and type imports", () => {
    const source = [
      'import path from "pathy";',
      'import { defineConfig } from "prisma/config";',
      'import type { NextConfig } from "next";',
    ].join("\n");
    expect(importedPackages(source)).toEqual(["next", "pathy", "prisma"]);
  });

  it("finds re-exports, dynamic imports and require", () => {
    const source = [
      'export { a } from "alpha";',
      'const b = await import("bravo");',
      'const c = require("charlie");',
    ].join("\n");
    expect(importedPackages(source)).toEqual(["alpha", "bravo", "charlie"]);
  });

  it("ignores relative specifiers", () => {
    expect(importedPackages('import { X } from "./e2e/constants";')).toEqual(
      [],
    );
  });

  // The `@/…` alias tsconfig paths and vitest map to src/ opens with `@`, so
  // a naive scoped-package read would report it as an undeclared `@/lib`.
  it("ignores the @/ alias rather than reading it as a scoped package", () => {
    expect(importedPackages('import { db } from "@/lib/db";')).toEqual([]);
  });

  it("still reports a genuine scoped package", () => {
    expect(importedPackages('import { P } from "@prisma/client";')).toEqual([
      "@prisma/client",
    ]);
  });

  it("ignores Node builtins with and without the node: prefix", () => {
    const source = 'import a from "node:path";\nimport b from "fs";';
    expect(importedPackages(source)).toEqual([]);
  });

  it("ignores a specifier that only appears in a comment", () => {
    // The header `prisma init` writes into prisma.config.ts is exactly this
    // shape, and it must not be read as a declaration of anything.
    const source = [
      "// This file was generated by Prisma, and assumes you have installed:",
      "// npm install --save-dev prisma dotenv",
      'import "dotenv/config";',
    ].join("\n");
    expect(importedPackages(source)).toEqual(["dotenv"]);
  });

  it("de-duplicates a package imported more than once", () => {
    const source = 'import "dotenv/config";\nimport { config } from "dotenv";';
    expect(importedPackages(source)).toEqual(["dotenv"]);
  });
});

/**
 * #76 regression guard. `prisma.config.ts` imported `dotenv` while
 * `package.json` declared it nowhere; it resolved only because
 * `prisma → @prisma/config → c12 → dotenv` hoisted a copy to
 * `node_modules/dotenv`. Hide that copy and `prisma migrate deploy` dies with
 * `Cannot find package 'dotenv'` — in the migrate initContainer, mid-deploy,
 * not in a test.
 *
 * These files are the ones at risk: Next bundles and traces everything under
 * `src/`, but nothing traces the root config files or the `tsx` entrypoints
 * the cluster invokes (the migrate initContainer, the review seed, the purge
 * CronJob). Anything they import has to be declared, or it is one dependency
 * upgrade away from vanishing.
 *
 * If this fails, declare the package it names — do not delete the file from
 * the list.
 */
describe("package.json declares what the unbundled files import (#76)", () => {
  const manifest = JSON.parse(
    readFileSync(join(process.cwd(), "package.json"), "utf8"),
  ) as {
    dependencies?: Record<string, string>;
    devDependencies?: Record<string, string>;
  };
  const declared = new Set([
    ...Object.keys(manifest.dependencies ?? {}),
    ...Object.keys(manifest.devDependencies ?? {}),
  ]);

  const UNBUNDLED = [
    "prisma.config.ts",
    "next.config.ts",
    "vitest.config.ts",
    "vitest.setup.ts",
    "playwright.config.ts",
    "eslint.config.mjs",
    "postcss.config.mjs",
    "prettier.config.mjs",
    "prisma/seed.ts",
    "prisma/scheduled-purge.ts",
    "scripts/check-env-drift.ts",
  ];

  it.each(UNBUNDLED)("%s imports only declared packages", (file) => {
    const source = readFileSync(join(process.cwd(), file), "utf8");
    for (const pkg of importedPackages(source)) {
      expect(
        declared,
        `${file} imports "${pkg}", which package.json declares nowhere — it ` +
          `resolves only while some other dependency hoists it (#76)`,
      ).toContain(pkg);
    }
  });
});
