apiVersion: v1
kind: Service
metadata:
  name: dlectroflow
  labels:
    {{- include "dlectroflow.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: dlectroflow
  ports:
    - port: 80
      targetPort: 3000
